[package]
name = "hello_rust"
version = "1.0.0"
description = "hello description"
license = "ISC"

[dependencies]
"_/cowsay" = "0.2.0"

[[module]]
name = "main"
source = "main.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.0.0-unstable"

[[command]]
name = "entry"
module = "entry"
